#!/bin/sh -e

docker rm rpi-ramdisk || true
docker build -t rpi-ramdisk .
echo
echo "Now starting a shell in the docker container. Run 'make -j8' to build."
echo "Copy build products out of the container before exiting the shell."
echo

docker run --name rpi-ramdisk -it rpi-ramdisk
