#!/bin/sh -e

docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t rpi-ramdisk .
docker run -v $PWD:/home/rpi-ramdisk/rpi-ramdisk --network host -e APT_HTTP_PROXY -e PYDOJOBS \
           --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged \
           --rm -it rpi-ramdisk
