#!/bin/sh -e

BOOT=boot-$1

rm -rf $BOOT
mkdir $BOOT

tar -xf firmware/firmware.tar.gz -C $BOOT/
tar -xf kernel/kernel-boot.tar.gz -C $BOOT/
tar -xf kernel/kernel7-boot.tar.gz -C $BOOT/

cp $1/initrd $BOOT/

cat <<EOF > $BOOT/config.txt
dtoverlay=pi3-disable-bt
dtparam=i2c_arm=on

# RTC
dtoverlay=i2c-rtc,ds3231

# Internal Audio
#dtparam=audio=on

gpu_mem=64
lcd_rotate=2

initramfs initrd
EOF

cat <<EOF > $BOOT/cmdline.txt
dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 elevator=deadline rootwait consoleblank=0
EOF

cd $BOOT
zip -r ../$BOOT.zip *
cd ..
