#!/bin/bash -e

ROOTDIR=root

rm -rf --one-file-system $ROOTDIR

http_proxy=$APT_HTTP_PROXY /usr/sbin/multistrap -d $ROOTDIR -f multistrap.conf

export QEMU_LD_PREFIX=$(readlink -f $ROOTDIR)

# If you want to use fakeroot/fakechroot for some reason,
# you will need to install them in multistrap.conf.
#MYCHROOT="fakechroot fakeroot chroot"
MYCHROOT="proot -0 -q qemu-arm-static -w / -r"

echo "Running preinst scripts..."

for script in $ROOTDIR/var/lib/dpkg/info/*.preinst; do
        [ "$script" = "$ROOTDIR/var/lib/dpkg/info/vpnc.preinst" ] && continue
        echo "I: run preinst script ${script##$ROOTDIR}"
        DPKG_MAINTSCRIPT_NAME=preinst \
        DPKG_MAINTSCRIPT_PACKAGE="`basename $script .preinst`" \
        $MYCHROOT $ROOTDIR ${script##$ROOTDIR} install
done

echo "Running dpkg --configure -a"

# don't run makedev
# we will create device nodes later, after we are done with the system dev
rm -f $ROOTDIR/var/lib/dpkg/info/makedev.postinst

# work around https://pad.lv/1727874
rm -f $ROOTDIR/var/lib/dpkg/info/raspbian-archive-keyring.postinst
ln -sf /usr/share/keyrings/raspbian-archive-keyring.gpg $ROOTDIR/etc/apt/trusted.gpg.d/

# work around PAM error
ln -s -f /bin/true $ROOTDIR/usr/bin/chfn

DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
 LC_ALL=C LANGUAGE=C LANG=C $MYCHROOT $ROOTDIR /usr/bin/dpkg --configure -a || true


echo "Preparing root..."

# no root password
$MYCHROOT $ROOTDIR passwd -d root

# initialize /etc/fstab
echo proc /proc proc defaults 0 0 > $ROOTDIR/etc/fstab

# hostname
echo $ROOTDIR > $ROOTDIR/etc/hostname

# write /etc/hosts
cat <<EOF > $ROOTDIR/etc/hosts
127.0.0.1       localhost
127.0.1.1       $ROOTDIR

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF

# The following profile fragment makes the terminal rows/cols
# be correct when logging in over serial
cat <<EOF > $ROOTDIR/etc/profile.d/resize.sh
resize() {

  old=\$(stty -g)
  stty raw -echo min 0 time 5

  printf '\033[18t' > /dev/tty
  IFS=';t' read -r _ rows cols _ < /dev/tty

  stty "\$old"

  # echo "cols:\$cols"
  # echo "rows:\$rows"
  stty cols "\$cols" rows "\$rows"
}

[ \$(tty) = /dev/ttyAMA0 ] && resize
EOF

echo "Configuring wired network..."

# reset default udev persistent-net rule
rm -f $ROOTDIR/etc/udev/rules.d/*_persistent-net.rules

# /etc/resolv.conf symlink
rm -f $ROOTDIR/etc/resolv.conf
$MYCHROOT $ROOTDIR ln -s "/run/systemd/resolve/resolv.conf" "/etc/resolv.conf"

$MYCHROOT $ROOTDIR /bin/systemctl reenable systemd-networkd
$MYCHROOT $ROOTDIR /bin/systemctl reenable systemd-resolved
$MYCHROOT $ROOTDIR /bin/systemctl reenable systemd-timesyncd
$MYCHROOT $ROOTDIR /bin/systemctl reenable systemd-networkd-wait-online.service

# time used by timesyncd if no other is available
touch $ROOTDIR/var/lib/systemd/clock

cat <<EOF > $ROOTDIR/etc/systemd/network/en.network
[Match]
Name=en*
[Network]
DHCP=yes
EOF


echo "Configuring wireless network..."

cat <<EOF > $ROOTDIR/etc/systemd/network/wlan0.network
[Match]
Name=wlan0
[Network]
DHCP=yes
EOF

cat <<EOF > $ROOTDIR/etc/systemd/system/wpa_supplicant@.service
[Unit]
Description=WPA supplicant daemon (interface-specific version)
Requires=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device
Before=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=/sbin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-%I.conf -Dnl80211,wext -i%I

[Install]
Alias=multi-user.target.wants/wpa_supplicant@%i.service
EOF

#$MYCHROOT $ROOTDIR /bin/systemctl reenable wpa_supplicant@wlan0.service

echo "Installing modules..."

tar -xf ../kernel/kernel-root.tar.gz -C $ROOTDIR
tar -xf ../kernel/kernel7-root.tar.gz -C $ROOTDIR

echo "Installing opt packages..."

tar -xf ../packages/qt/qt.tar.gz -C $ROOTDIR
tar -xf ../packages/gstreamer/gstreamer.tar.gz -C $ROOTDIR
tar -xf ../packages/rygel/rygel.tar.gz -C $ROOTDIR

$ROOTDIR/sbin/ldconfig -r $ROOTDIR

#$MYCHROOT $ROOTDIR /bin/systemctl reenable qmldemo.service


echo "Cleaning up..."

./cleanup $ROOTDIR excludes.conf > /dev/null
mkdir -p $ROOTDIR/etc/dpkg/dpkg.cfg.d
cp excludes.conf $ROOTDIR/etc/dpkg/dpkg.cfg.d/

$MYCHROOT $ROOTDIR udevadm hwdb --update --usr

echo "Misc housekeeping..."

ln -sf /sbin/init $ROOTDIR/init
ln -sf /proc/mounts $ROOTDIR/etc/mtab

echo "Creating minimal device nodes..."

# this must be done last. if the fakeroot devices exist on the system,
# fakechroot wont be able to read from them, which breaks systemd setup.
cd $ROOTDIR/dev
fakeroot /sbin/MAKEDEV std
cd ../..

echo "Packing rootfs..."

$MYCHROOT $ROOTDIR sh -c "cd / && find * -xdev -not \( \
              -path host-rootfs -prune \
              -path run -prune \
              -path proc -prune \
              -path sys -prune \
              -path boot -prune \
           \) | cpio --create -H newc" | gzip -9 > initrd
