import os

env = Environment(tools=[])

try:
    env['ENV']['http_proxy'] = os.environ['APT_HTTP_PROXY']
except KeyError:
    print("Don't forget to set up apt-cacher-ng")

stage = Dir('stage/')

firmware = env.Command('firmware.tar.gz', ['multistrap.conf', 'cmdline.txt', 'config.txt'], [

    'rm -rf --one-file-system ${STAGE}',

    'mkdir -p ${STAGE}/etc/apt/trusted.gpg.d/',
    'gpg --export 82B129927FA3303E > ${STAGE}/etc/apt/trusted.gpg.d/raspberrypi-archive-keyring.gpg',
    '/usr/sbin/multistrap -d ${STAGE} -f ${SOURCES[0]}',

    'cp ${SOURCES[1:]} ${STAGE}/boot/',

    'tar -C ${STAGE}/boot/ -czvf ${TARGET} .',

], STAGE=stage)

env.Clean(firmware, stage)

